include other.conf
globinclude kitty.d/**/*.conf
envinclude KITTY_CONF_*

font_family Lilex Nerd Font Mono
font_size 9.5
disable_ligatures never

background_opacity 0.85
dynamic_background_opacity yes

window_padding_width 0
window_margin_width 0

placement_strategy center
remember_window_size yes
confirm_os_window_close 0

cursor_shape beam
cursor_beam_thickness 1.8
cursor_blink_interval 0

tab_bar_style powerline
tab_powerline_style slanted
tab_bar_edge top

background #1a1b26
foreground #c0caf5


repaint_delay 10
input_delay 0
sync_to_monitor yes
enable_audio_bell no

